config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'user_photos/delete'
  resources :users
  get  "/signup",  to: "users#new"
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :photos, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :profiles, only: [:show, :index, :edit, :update, :destroy]
  resources :likes, only: [:create]
  resources :dislikes, only: [:create]
  resources :matches, only: [:index]
  resources :admin, only: [:index]
  resources :messages, only: [:show, :create, :index]
  get '/messages/:user_id/show', to: 'messages#show', as: 'show_user_message'

  namespace :admin do
    resources :matches_manager, only: [:index]
    resources :user_manager, only: [:index]
  end

  namespace :admin do
    namespace :user_manager do
      resources :users, only: [:show, :edit, :update, :destroy]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_photos
  has_many :photos, through: :user_photo
  has_many :outgoing_likes, class_name: "Like", foreign_key: "liker_id", dependent: :destroy
  has_many :liked_users, through: :outgoing_likes, source: :liked
  has_many :incoming_likes, class_name: "Like", foreign_key: "liked_id", dependent: :destroy
  has_many :likers, through: :incoming_likes, source: :liker
  has_many :outgoing_dislikes, class_name: "Dislike", foreign_key: "disliker_id", dependent: :destroy
  has_many :disliked_users, through: :outgoing_dislikes, source: :disliked
  has_many :incoming_dislikes, class_name: "Dislike", foreign_key: "disliked_id", dependent: :destroy
  has_many :dislikers, through: :incoming_dislikes, source: :disliker
  has_many :sent_messages, class_name: 'Message', foreign_key: 'sender_id'
  has_many :received_messages, class_name: 'Message', foreign_key: 'recipient_id'
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  normalizes :email, with: ->(email) {email.strip.downcase}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :first_name, presence: true, length: { minimum: 2, maximum: 25 }
  validates :last_name, presence: true, length: { minimum: 2, maximum: 25 }
  validates :mobile, presence: true, length: { minimum: 10, maximum: 15 }
  validates :email, presence: true, length: { minimum: 6, maximum: 254 },
              format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  validates :country, presence: true, length: { minimum: 4, maximum: 56 }
  validates :state, presence: true, length: { maximum: 100 }
  validates :city, presence: true, length: { maximum: 100 }
  validates :birthdate, presence: true
  validates :gender, inclusion: { in: %w(Male Female) }, allow_blank: true
  validates :sexual_orientation, inclusion: { in: %w(Male Female) }, allow_blank: true
  validates :gender_interest, inclusion: { in: %w(Male Female) }, allow_blank: true
  validates :school, length: { maximum: 100 }
  validates :bio, length: { maximum: 1000 }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, on: :create

  class << self
    # Returns the hash digest of the given string.
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/admin/user_manager/users_controller.rb
class Admin::UserManager::UsersController < ApplicationController
  include LoggedInRestrictions
  include AdminRestrictions

  def show
    @user = User.find_by(id: params[:id])
    @user_photos = UserPhoto.where(user_id: params[:id])
    @matches = Like.where(liker_id: Like.where(liker_id: params[:id]).pluck(:liked_id), liked_id: params[:id]).paginate(page: params[:page]).per_page(10)
  end

  def edit
    store_last_page
    @user = User.find(params[:id])
    @user_photos = UserPhoto.where(user_id: params[:id])
  end

  def update
    @user = User.find(params[:id])

    if params[:user][:images] != [""]
      params[:user][:images].each do |image|
        if UserPhoto.where(user_id: params[:id]).count < 5
          next unless image.is_a?(ActionDispatch::Http::UploadedFile)
          cloudinary_upload = Cloudinary::Uploader.upload(image.tempfile, folder: "your_folder_name")
          photo = Photo.create(link: cloudinary_upload['secure_url'])
          user_photo = UserPhoto.create(user_id: params[:id], photo_id: photo.id)
        else
          flash[:danger] = "Maximum of 5 photos are allowed"
        end
      end
    end

    if @user.update(user_params)
      redirect_to admin_user_manager_user_path
      flash[:success] = "Profile was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_user_manager_user_path
    flash[:success] = "User was successfully destroyed."
  end

  private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :mobile, :email, :birthdate, :gender, :sexual_orientation, :gender_interest, :country, :state, :city, :school, :bio, :is_admin, :password, :password_confirmation)
    end
end

app/controllers/admin/user_manager_controller.rb
class Admin::UserManagerController < ApplicationController
  include LoggedInRestrictions
  include AdminRestrictions

  def index
    @users = User.paginate(page: params[:page]).per_page(10)
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    uploaded_file = params[:user][:image]
    response = Cloudinary::Uploader.upload(uploaded_file)
    photo = Photo.new(link: response['secure_url'])
    photo.save

    if @user.save
      new_user_photo = UserPhoto.new(user_id: @user.id, photo_id: photo.id)
      new_user_photo.save
      reset_session
      log_in @user
      flash[:success] = "Welcome to the Dating Web App!"
      redirect_to root_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
  end

  def edit
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
    flash[:success] = "User was successfully destroyed."
  end

  private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :mobile, :email, :birthdate, :gender, :sexual_orientation, :gender_interest, :country, :state, :city, :school, :bio, :is_admin, :password, :password_confirmation)
    end
end

app/helpers/admin/user_manager/users_helper.rb
module Admin::UserManager::UsersHelper
end

app/helpers/admin/user_manager_helper.rb
module Admin::UserManagerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/user_manager/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>Edit Profile</h1>
      <%= form_with(model: @user, url: admin_user_manager_user_path(@user), method: :patch, local: true) do |form| %>
        <div>
          <%= form.label :first_name, "First name" %>
          <%= form.text_field :first_name, class: 'form-control', required: true, value: @user.first_name %>
        </div>
        <div>
          <%= form.label :last_name, "Last name" %>
          <%= form.text_field :last_name, class: 'form-control', required: true, value: @user.last_name %>
        </div>
        <div>
          <%= form.label :mobile, "Mobile" %>
          <%= form.text_field :mobile, class: 'form-control', required: true, value: @user.mobile %>
        </div>
        <div>
          <%= form.label :email, "Email" %>
          <%= form.text_field :email, class: 'form-control', required: true, value: @user.email %>
        </div>
        <div>
          <%= form.label :birthdate, "Birthdate" %>
          <%= form.date_field :birthdate, class: 'form-control', required: true, value: @user.birthdate %>
        </div>
        <div>
          <%= form.label :gender, class: "form-label" %>
          <%= form.select :gender, options_for_select(['Male', 'Female'], @user.gender), { include_blank: false }, class: 'form-control', aria: { label: 'Default select example' }  %>
        </div>
        <div>
          <%= form.label :sexual_orientation, class: "form-label" %>
          <%= form.select :sexual_orientation, options_for_select(['Male', 'Female'], @user.sexual_orientation), { include_blank: false }, class: 'form-control', aria: { label: 'Default select example' }%>
        </div>
        <div>
          <%= form.label :gender_interest, class: "form-label" %>
          <%= form.select :gender_interest, options_for_select(['Male', 'Female'], @user.gender_interest), { include_blank: false }, class: 'form-control', aria: { label: 'Default select example' } %>
        </div>
        <div>
          <%= form.label :country, "Country" %>
          <%= form.text_field :country, class: 'form-control', required: true, value: @user.country %>
        </div>
        <div>
          <%= form.label :state, "State" %>
          <%= form.text_field :state, class: 'form-control', required: true, value: @user.state %>
        </div>
        <div>
          <%= form.label :city, "City" %>
          <%= form.text_field :city, class: 'form-control', required: true, value: @user.city %>
        </div>
        <div>
          <%= form.label :school, "School" %>
          <%= form.text_field :school, class: 'form-control', required: true, value: @user.school %>
        </div>
        <div>
          <%= form.label :bio %>
          <%= form.text_area :bio, class: 'form-control', value: @user.bio %>
        </div>
        <div class="form-check">
          <%= form.label :is_admin %>
          <%= form.check_box :is_admin, class: 'form-check-input', value: @user.is_admin %>
        </div>
        <div>
          <%= form.label :password %>
          <%= form.password_field :password, class: 'form-control' %>
        </div>
        <div>
          <%= form.label :password_confirmation, "Confirmation" %>
          <%= form.password_field :password_confirmation, class: 'form-control' %>
        </div>

        <h2 class="text-center">Edit Photo Gallery</h2>
        <%= form.label 'Current Photos:' %><br>
        <% if @user_photos.count == 0 %>
          <i>This user does not have any photos yet.</i>
        <% else %>
          <% @user_photos.each  do |user_photo| %>
            <div class="photo-container">
              <%= image_tag user_photo.photo.link, alt: user_photo.photo.link, height: 100 %>
              <%= link_to "x", user_photos_delete_path(id: user_photo.id, user_id: @user.id), method: :delete, data: { confirm: "Are you sure you want to delete this Photo?" }, class: 'btn btn-danger btn-xs' %>
            </div>
          <% end %>
        <% end %><br><br>
        <%= form.label 'Upload Photos:' %><br>
        <%= form.file_field :images, multiple: true %><br>


        <div class="col-md-12 text-center">
          <%= form.submit "Update profile", class: "btn btn-primary btn-sm" %>
          <%= link_to 'Cancel', admin_user_manager_user_path, class: "btn btn-primary btn-sm" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/user_manager/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
    <h1>Profile</h1>

      <strong>First Name:</strong> <%= @user.first_name %><br>
      <strong>Last Name:</strong> <%= @user.last_name %><br>
      <strong>Mobile:</strong> <%= @user.mobile %><br>
      <strong>Email:</strong> <%= @user.email %><br>
      <strong>Birthdate:</strong> <%= @user.birthdate %><br>
      <strong>Gender:</strong> <%= @user.gender %><br>
      <strong>Sexual Orientation:</strong> <%= @user.sexual_orientation %><br>
      <strong>Gender Interest:</strong> <%= @user.gender_interest %><br>
      <strong>Country:</strong> <%= @user.country %><br>
      <strong>State:</strong> <%= @user.state %><br>
      <strong>City:</strong> <%= @user.city %><br>
      <strong>School:</strong> <%= @user.school %><br>
      <strong>Bio:</strong> <%= @user.bio %><br>
      <strong>Is Admin:</strong> <%= @user.is_admin %><br>
    <div>
      <h2>Photo Gallery</h2>
      <% if @user_photos.count == 0 %>
        <i>This user does not have any photos yet.</i>
      <% else %>
        <% @user_photos.each do |user_photo| %>
          <%= image_tag(user_photo.photo.link, alt: "Description of the image", height: "100", width: "100") %>
        <% end %>
      <% end %>
    </div>
    <br><br>
    <div class="col-md-12 text-center">
      <%= link_to 'Edit Profile', edit_admin_user_manager_user_path(@user.id), class: "btn btn-primary btn-sm" %>
      <%= link_to 'Back', admin_user_manager_index_path, class: "btn btn-primary btn-sm" %>
    </div>
    <br><br>
    <div>
      <h2>User Matches</h2>
      <% if @matches.length == 0 %>
        <br><br><br><br>
          <div class="text-center"><i>This user does not have any matches yet.</i></div>
        <br><br><br><br>
      <% end %>
      <div>
        <% if @matches.length > 0 %>
          <div class="table_user_manager-destkop table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Primary Photo</th>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Location</th>
                  <th>Bio</th>
                  <th>Gallery</th>
                </tr>
              </thead>
              <tbody>
                <% @matches.each_with_index do |match, index| %>
                  <tr>
                    <td><%= index+1 %></td>
                    <td><%= image_tag(UserPhoto.where(user_id: match.liker.id).first.photo.link, alt: "Description of the image", height: "100", width: "100", class: "img-thumbnail") %></td>
                    <td><%= match.liker.first_name %></td>
                    <td><%= match.liker.last_name %></td>
                    <td><%= match.liker.country %>, <%= match.liker.state %>, <%= match.liker.city %></td>
                    <td><%= match.liker.bio %></td>
                    <td>
                      <% UserPhoto.where(user_id: match.liker.id).each do |user_photo| %>
                        <%= image_tag(user_photo.photo.link, alt: "Description of the image", height: "100", width: "100") %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <div class="table_user_manager-sp">
            <table class="table table-striped">
              <thead class="thead-dark">
                <tr>
                  <th>User</th>
                  <th scope="col">Primary Photo</th>
                </tr>
              </thead>
              <tbody>
                <% @matches.each_with_index do |match, index| %>
                  <tr>
                    <td>
                      <br>
                      <b>#</b>&nbsp;<%= index+1 %><br>
                      <b>First name:</b>&nbsp;<%= match.liker.first_name %><br>
                      <b>Last name:</b>&nbsp;<%= match.liker.last_name %><br>
                      <b>Location:</b>&nbsp;<%= match.liker.country %>, <%= match.liker.state %>, <%= match.liker.city %><br>
                      <b>Bio:</b>&nbsp;<%= match.liker.bio %><br>
                      <b>Gallery:</b>&nbsp;
                      <% UserPhoto.where(user_id: match.liker.id).each do |user_photo| %>
                        <%= image_tag(user_photo.photo.link, alt: "Description of the image", height: "70", width: "70", class: "img-thumbnail") %>
                      <% end %><br>
                      <br><br>
                    </td>
                    <td>
                      <br><br><%= image_tag(UserPhoto.where(user_id: match.liker.id).first.photo.link, alt: "Description of the image", height: "100", width: "100", class: "img-thumbnail") %><br>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          </div>
          <%= will_paginate @matches %>
        <% end %>
      </div>
    </div>
  </div>
</div>