config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'user_photos/delete'
  resources :users
  get  "/signup",  to: "users#new"
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :photos, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :profiles, only: [:show, :index, :edit, :update, :destroy]
  resources :likes, only: [:create]
  resources :dislikes, only: [:create]
  resources :matches, only: [:index]
  resources :admin, only: [:index]
  resources :messages, only: [:show, :create, :index]
  get '/messages/:user_id/show', to: 'messages#show', as: 'show_user_message'

  namespace :admin do
    resources :matches_manager, only: [:index]
    resources :user_manager, only: [:index]
  end

  namespace :admin do
    namespace :user_manager do
      resources :users, only: [:show, :edit, :update, :destroy]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  include LoggedInRestrictions
  include SessionsHelper
  before_action :set_users, only: [:show, :create]
  before_action :update_unread_messages, only: [:show, :create]

  def show
    store_last_page
    @message = Message.new
    @messages = Message.where(sender_id: [params[:user_id], current_user.id]).where(recipient_id: [params[:user_id], current_user.id]).order(created_at: :asc)
  end

  def create
    @message = current_user.sent_messages.build(message_params)
    if @message.save
      redirect_to show_user_message_path(user_id: params[:user_id])
    else
      puts "message is saved and this is the error #{@message.errors.full_messages}"
      render :new
    end
  end

  def index
    store_last_page
    @matches = Like.where(liker_id: Like.where(liker_id: current_user.id).pluck(:liked_id), liked_id: current_user.id)
  end

  private

  def message_params
    params.require(:message).permit(:body, :recipient_id)
  end

  def set_users
    @users = User.where.not(id: current_user.id)
    @recipient = User.find(params[:recipient_id]) if params[:recipient_id]
  end

  def update_unread_messages
    Message.where(recipient_id: current_user.id).where(sender_id: params[:user_id]).update(seen: true)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.erb
<div class="container">
  <h1>Message</h1>

  <div class="row">
    <% if @matches.length == 0 %>
      <br><br><br><br>
        <div class="text-center"><i>You have no matches yet.</i></div>
      <br><br><br><br>
    <% end %>
    <div class="col-md-6 col-md-offset-3">
      <% if @matches.length > 0 %>
        <% @matches.each do |match| %>
          <%= link_to show_user_message_path(user_id: match.liker.id) do %>
            <div class="messages_container">
              <div class="messages_container-left">
                <%= image_tag(UserPhoto.where(user_id: match.liker.id).first.photo.link, alt: "Description of the image", height: "50", width: "50", class: "rounded-circle") %>
                <b><%= match.liker.first_name %>&nbsp;<%= match.liker.last_name %>:</b>
              </div>
              <div class="messages_container-right">
                <% if Message.where(sender_id: [match.liker.id, current_user.id]).where(recipient_id: [match.liker.id, current_user.id]).order(created_at: :asc).last==nil %>
                  <i>Say hello to your new match!</i><br>
                  <i><%= match.created_at.strftime("%B %e, %Y, %I:%M %p") %></i>
                <% else %>
                  <% if Message.where(sender_id: [match.liker.id, current_user.id]).where(recipient_id: [match.liker.id, current_user.id]).order(created_at: :asc).last.sender_id == current_user.id %>
                    You: <%= truncate(Message.where(sender_id: [match.liker.id, current_user.id]).where(recipient_id: [match.liker.id, current_user.id]).order(created_at: :asc).last.body, length: 20) %><br>
                    <i><%= Message.where(sender_id: [match.liker.id, current_user.id]).where(recipient_id: [match.liker.id, current_user.id]).order(created_at: :asc).last.created_at.strftime("%B %e, %Y, %I:%M %p") %></i>
                  <% else %>
                    <% if Message.where(sender_id: [match.liker.id, current_user.id]).where(recipient_id: [match.liker.id, current_user.id]).order(created_at: :asc).last.seen %>
                      <%= truncate(Message.where(sender_id: [match.liker.id, current_user.id]).where(recipient_id: [match.liker.id, current_user.id]).order(created_at: :asc).last.body, length: 20) %><br>
                      <i><%= Message.where(sender_id: [match.liker.id, current_user.id]).where(recipient_id: [match.liker.id, current_user.id]).order(created_at: :asc).last.created_at.strftime("%B %e, %Y, %I:%M %p") %></i>
                    <% else %>
                      <b><%= truncate(Message.where(sender_id: [match.liker.id, current_user.id]).where(recipient_id: [match.liker.id, current_user.id]).order(created_at: :asc).last.body, length: 20) %></b><br>
                      <i><%= Message.where(sender_id: [match.liker.id, current_user.id]).where(recipient_id: [match.liker.id, current_user.id]).order(created_at: :asc).last.created_at.strftime("%B %e, %Y, %I:%M %p") %></i>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/messages/show.html.erb
<div class="container">
  <h1>Message</h1>
  <div class="row messages_row">
    <div class="col-md-6 col-md-offset-3 messenger" id="scrollableContent">
      <% @messages.each do |message| %>
        <% if message.sender_id == current_user.id %>
          <div class="message message--right">
            <div class="message_mine"><%= message.body %></div>
            <small>
              <i><%= message.created_at.strftime("%B %e, %Y, %I:%M %p") %></i>
              <br>
              <% if message.seen %>
                <span class="seen"><i>Seen</i></span>
              <% end %>
            </small>
          </div>
        <% else %>
          <div class="message">
            <div class="message_to_me">
              <b><%= message.sender.first_name %>&nbsp;<%= message.sender.last_name %>:</b> <%= message.body %>
            </div>
            <small>
              <i><%= message.created_at.strftime("%B %e, %Y, %I:%M %p") %></i>
              <br>
              <% if message.seen %>
                <span class="seen"><i>Seen</i></span>
              <% end %>
            </small>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-6 col-md-offset-3 messenger_textarea_container">
      <%= form_with(model: @message, url: messages_path(user_id: params[:user_id])) do |form| %>
        <%= form.hidden_field :recipient_id, value: params[:user_id] %>
        <div class="messenger_textarea_frame">
          <%= form.text_area :body, class:"messenger_textarea form-control" %>
          <%= form.submit "Send", class: "message_submit" %>
        </div>
      <% end %>
    </div>
  </div>
</div>