config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'user_photos/delete'
  resources :users
  get  "/signup",  to: "users#new"
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :photos, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :profiles, only: [:show, :index, :edit, :update, :destroy]
  resources :likes, only: [:create]
  resources :dislikes, only: [:create]
  resources :matches, only: [:index]
  resources :admin, only: [:index]
  resources :messages, only: [:show, :create, :index]
  get '/messages/:user_id/show', to: 'messages#show', as: 'show_user_message'

  namespace :admin do
    resources :matches_manager, only: [:index]
    resources :user_manager, only: [:index]
  end

  namespace :admin do
    namespace :user_manager do
      resources :users, only: [:show, :edit, :update, :destroy]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/admin/user_manager/users_controller.rb
class Admin::UserManager::UsersController < ApplicationController
  include LoggedInRestrictions
  include AdminRestrictions

  def show
    @user = User.find_by(id: params[:id])
    @user_photos = UserPhoto.where(user_id: params[:id])
    @matches = Like.where(liker_id: Like.where(liker_id: params[:id]).pluck(:liked_id), liked_id: params[:id]).paginate(page: params[:page]).per_page(10)
  end

  def edit
    store_last_page
    @user = User.find(params[:id])
    @user_photos = UserPhoto.where(user_id: params[:id])
  end

  def update
    @user = User.find(params[:id])

    if params[:user][:images] != [""]
      params[:user][:images].each do |image|
        if UserPhoto.where(user_id: params[:id]).count < 5
          next unless image.is_a?(ActionDispatch::Http::UploadedFile)
          cloudinary_upload = Cloudinary::Uploader.upload(image.tempfile, folder: "your_folder_name")
          photo = Photo.create(link: cloudinary_upload['secure_url'])
          user_photo = UserPhoto.create(user_id: params[:id], photo_id: photo.id)
        else
          flash[:danger] = "Maximum of 5 photos are allowed"
        end
      end
    end

    if @user.update(user_params)
      redirect_to admin_user_manager_user_path
      flash[:success] = "Profile was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_user_manager_user_path
    flash[:success] = "User was successfully destroyed."
  end

  private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :mobile, :email, :birthdate, :gender, :sexual_orientation, :gender_interest, :country, :state, :city, :school, :bio, :is_admin, :password, :password_confirmation)
    end
end

app/controllers/admin/user_manager_controller.rb
class Admin::UserManagerController < ApplicationController
  include LoggedInRestrictions
  include AdminRestrictions

  def index
    @users = User.paginate(page: params[:page]).per_page(10)
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/admin/user_manager/users_helper.rb
module Admin::UserManager::UsersHelper
end

app/helpers/admin/user_manager_helper.rb
module Admin::UserManagerHelper
end

app/views/admin/user_manager/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 col-md-offset-1">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><%= link_to "Home", root_path %></li>
          <li class="breadcrumb-item"><%= link_to "Admin", admin_index_path %></li>
          <li class="breadcrumb-item"><%= link_to "User Manager", admin_user_manager_index_path %></li>
        </ol>
      </nav>
      <h1>User Manager</h1>
      <% if @users.length == 0 %>
        <br><br><i>The User database is empty.</i>
      <% else %>
      <div class="table_user_manager-destkop table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>#</th>
              <th style="text-align: center;">Primary Photo</th>
              <th style="text-align: center;">First Name</th>
              <th style="text-align: center;">Last Name</th>
              <th style="text-align: center;">Action</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each_with_index do |user, index| %>
              <tr>
                <td><%= index+1 %> </td>
                <td style="text-align: center; justify-self: center; align-items: center;"><%= image_tag user.user_photos.first.photo.link, height: "100", width: "100", class: "img-thumbnail" %></td>
                <td style="text-align: center;"><%= user.first_name %></td>
                <td style="text-align: center;"><%= user.last_name %></td>
                <td style="text-align: center;">
                  <%= link_to 'View', admin_user_manager_user_path(user), class: 'btn btn-primary btn-sm' %>
                  <%= link_to 'Edit', edit_admin_user_manager_user_path(user), class: 'btn btn-secondary btn-sm' %>
                  <%= link_to "Delete", user, data: { "turbo-method": :delete, turbo_confirm: "You sure?"}, class: "btn btn-danger btn-sm" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="table_user_manager-sp">
        <table class="table table-striped">
          <thead class="thead-dark">
            <tr>
              <th>User</th>
              <th scope="col">Primary Photo</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each_with_index do |user, index| %>
              <tr>
                <td>
                  <br>
                  <b>#</b>&nbsp;<%= index+1 %><br>
                  <b>First name:</b>&nbsp;<%= user.first_name %><br>
                  <b>Last name:</b>&nbsp;<%= user.last_name %><br>
                  <b>Actions:</b><br>
                  <%= link_to 'View', admin_user_manager_user_path(user), class: 'btn btn-primary btn-sm' %>
                  <%= link_to 'Edit', edit_admin_user_manager_user_path(user), class: 'btn btn-secondary btn-sm' %>
                  <%= link_to "Delete", user, data: { "turbo-method": :delete, turbo_confirm: "You sure?"}, class: "btn btn-danger btn-sm" %>
                  <br><br>
                </td>
                <td>
                  <br>
                  &nbsp;<%= image_tag user.user_photos.first.photo.link, height: "100", width: "100", class: "img-thumbnail" %><br>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <%= will_paginate @users %>
      <% end %>
    </div>
  </div>
</div>