config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'user_photos/delete'
  resources :users
  get  "/signup",  to: "users#new"
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :photos, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :profiles, only: [:show, :index, :edit, :update, :destroy]
  resources :likes, only: [:create]
  resources :dislikes, only: [:create]
  resources :matches, only: [:index]
  resources :admin, only: [:index]
  resources :messages, only: [:show, :create, :index]
  get '/messages/:user_id/show', to: 'messages#show', as: 'show_user_message'

  namespace :admin do
    resources :matches_manager, only: [:index]
    resources :user_manager, only: [:index]
  end

  namespace :admin do
    namespace :user_manager do
      resources :users, only: [:show, :edit, :update, :destroy]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dislike.rb
class Dislike < ApplicationRecord
  belongs_to :disliker, class_name: "User"
  belongs_to :disliked, class_name: "User"

  validates :disliker, presence: true
  validates :disliked, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :liker, class_name: "User"
  belongs_to :liked, class_name: "User"

  validates :liker, presence: true
  validates :liked, presence: true
end

app/models/match.rb
class Match < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_many :user_photos
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_photos
  has_many :photos, through: :user_photo
  has_many :outgoing_likes, class_name: "Like", foreign_key: "liker_id", dependent: :destroy
  has_many :liked_users, through: :outgoing_likes, source: :liked
  has_many :incoming_likes, class_name: "Like", foreign_key: "liked_id", dependent: :destroy
  has_many :likers, through: :incoming_likes, source: :liker
  has_many :outgoing_dislikes, class_name: "Dislike", foreign_key: "disliker_id", dependent: :destroy
  has_many :disliked_users, through: :outgoing_dislikes, source: :disliked
  has_many :incoming_dislikes, class_name: "Dislike", foreign_key: "disliked_id", dependent: :destroy
  has_many :dislikers, through: :incoming_dislikes, source: :disliker
  has_many :sent_messages, class_name: 'Message', foreign_key: 'sender_id'
  has_many :received_messages, class_name: 'Message', foreign_key: 'recipient_id'
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  normalizes :email, with: ->(email) {email.strip.downcase}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :first_name, presence: true, length: { minimum: 2, maximum: 25 }
  validates :last_name, presence: true, length: { minimum: 2, maximum: 25 }
  validates :mobile, presence: true, length: { minimum: 10, maximum: 15 }
  validates :email, presence: true, length: { minimum: 6, maximum: 254 },
              format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  validates :country, presence: true, length: { minimum: 4, maximum: 56 }
  validates :state, presence: true, length: { maximum: 100 }
  validates :city, presence: true, length: { maximum: 100 }
  validates :birthdate, presence: true
  validates :gender, inclusion: { in: %w(Male Female) }, allow_blank: true
  validates :sexual_orientation, inclusion: { in: %w(Male Female) }, allow_blank: true
  validates :gender_interest, inclusion: { in: %w(Male Female) }, allow_blank: true
  validates :school, length: { maximum: 100 }
  validates :bio, length: { maximum: 1000 }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, on: :create

  class << self
    # Returns the hash digest of the given string.
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/models/user_photo.rb
class UserPhoto < ApplicationRecord
  belongs_to :user
  belongs_to :photo, dependent: :destroy

  validate :validate_user_photo_limit, on: :create

  private

  def validate_user_photo_limit
    if user.user_photos.count >= 5
      errors.add(:base, "User can only have maximum of 5 photos")
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  include LoggedInRestrictions
  include AdminRestrictions

  def index
    store_last_page
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include SessionsHelper

  def index
    if current_user
      likes = Like.where(liker: current_user.id).pluck(:liked_id)
      dislikes = Dislike.where(disliker: current_user.id).pluck(:disliked_id)
      judged_users = likes + dislikes
      judged_users_uniq = judged_users.uniq
      @filtered_user = User.where(gender: current_user.gender_interest).where.not(id: judged_users_uniq).order("RANDOM()").limit(1).first
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Dating Web App - Official Website"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/dislikes_helper.rb
module DislikesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.encrypted[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.encrypted[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    reset_session
    @current_user = nil
  end
end

app/helpers/user_photos_helper.rb
module UserPhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<%= javascript_include_tag('splide.js') %>
<div class="container">
  <div class="row">
    <div class="home">
      <% if current_user  %>
        <h1>Find your match</h1>
        <div class="splide d-flex justify-content-center">
          <div class="splide__track">
            <ul class="splide__list">
              <% if @filtered_user %>
                <li class="splide__slide"></li>
                <li class="splide__slide">
                  <div class="row">
                    <div class="col-md-4">
                      <b>Photo</b>
                      <%= image_tag(UserPhoto.where(user_id: @filtered_user.id).first.photo.link, alt: "Description of the image", class: "img-thumbnail") %>
                    </div>
                    <div class="col-md-8">
                      <b>Gallery</b>
                      <div class="row">
                        <% UserPhoto.where(user_id: @filtered_user.id).each do |user_photo| %>

                            <%= image_tag(user_photo.photo.link, alt: "Description of the image", height: "100") %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                  <div class="row mt-3">
                    <div class="col-md-6">
                      <b>First Name:</b>
                      <%= @filtered_user.first_name %>
                    </div>
                    <div class="col-md-6">
                      <b>Last Name:</b>
                      <%= @filtered_user.last_name %>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-6">
                      <b>Location:</b>
                      <%= @filtered_user.country %>, <%= @filtered_user.state %>, <%= @filtered_user.city %>
                    </div>
                    <div class="col-md-6">
                      <b>Bio:</b>
                      <%= @filtered_user.bio %>
                    </div>
                  </div>
                  <%= button_to "Like", likes_path(liked_id: @filtered_user.id), method: :create, class: 'btn btn-success btn-sm', id:"successBtn" %>
                  <%= button_to "Disike", dislikes_path(disliked_id: @filtered_user.id), method: :create, class: 'btn btn-danger btn-sm', id:"dangerBtn" %>
                </li>
                <li class="splide__slide"></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
      <% end %>      
    </div>
      <% if current_user  %>
        <% unless @filtered_user %>
          <br><br><br><br>
          <div class="text-center"><i>No new users to like or dislike</i></div>
          <br><br><br><br>
        <% end %>
      <% else %>
        <br><br><br><br>
          <div class="text-center"><i>Sign up and Log in to find your match</i></div>
        <br><br><br><br>
      <% end %>
  </div>
</div>